// Generated by CoffeeScript 1.6.2
(function() {
  var randomShapeMatch, shapeContextMatch;

  randomShapeMatch = function(shape1, shape2) {
    return Math.random();
  };

  shapeContextMatch = function(shape1, shape2) {
    return 0;
  };

}).call(this);
